name: first workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "welcome to my first Github Action workflow!"
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: list repository files
        run: ls -la
